fabioz/Pydev

plugins/org.python.pydev.shared_interactive_console/src/org/python/pydev/shared_interactive_console/console/ui/internal/ScriptConsoleDocumentListener.java

If output from the interpreter is split, the console input prompt can become corrupted.
This fix preserves the read-only portion of the prompt.

PyDev-490 / RAP-200 Fix corruption of the input prompt

---

plugins/com.python.pydev.refactoring/src/com/python/pydev/refactoring/wizards/rename/PyRenameRefactoringWizard.java

Fix a typo in the Rename Refactoring Wizard (foder -> folder)

Fix typo in PyRenameRefactoringWizard.java

---

plugins/org.python.pydev/src/org/python/pydev/editor/codefolding/CodeFoldingSetter.java
plugins/org.python.pydev/src/org/python/pydev/editor/codefolding/FoldingEntry.java
plugins/org.python.pydev/src/org/python/pydev/editor/codefolding/PyDevCodeFoldingPrefPage.java
plugins/org.python.pydev/src/org/python/pydev/editor/codefolding/PyProjectionAnnotation.java
plugins/org.python.pydev/src/org/python/pydev/plugin/preferences/PydevPrefsInitializer.java
plugins/org.python.pydev/tests/org/python/pydev/editor/codefolding/CodeFoldingSetterTest.java

With this new preference users can select to automatically collapse
multi-line comments whenever the file is opened. The idea here is to reduce
the visual noise when opening a file so a user can concentrate on the actual
source.
The default for this is off to keep compatibility with older PyDev versions
so users do not suddenly miss their documentation.

Support automatic folding of comments when opening a file

---

plugins/org.python.pydev/src/org/python/pydev/ui/pythonpathconf/InterpreterInfo.java

It's in the same boat as wx where it's not analyzable without being
inspected.
Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>

Add gi to forcedLibs to prevent errors.

---

plugins/org.python.pydev.jython/jysrc/pyedit_wrap_expression.py

References:
https://github.com/aptana/Pydev/pull/56
https://github.com/aptana/Pydev/pull/18
Now respects indent settings like Fabioz originally suggested.

Add jython script plugin for (un-)wrapping bracketed expressions.

---

plugins/org.python.pydev/pysrc/_pydev_runfiles/pydev_runfiles.py

Also drops support for Django < 1.7.

Make test runner work with Django >= 1.8 (#PyDev 614)

---

features/org.python.pydev.feature/pom.xml
features/org.python.pydev.p2-repo/category.xml
pom.xml

These allow to look at PyDev sources for debugging or learning when using
a PyDev binary distribution and integrating it with other plugins/projects.
Add the source feature to the category so it shows up in the p2 repository
and hence is consumable by the users.

Introduce source features/plugins

---

plugins/org.python.pydev.shared_core/src/org/python/pydev/shared_core/resource_stubs/WorkspaceStub.java
plugins/org.python.pydev/src/org/python/pydev/editor/PyEditConfiguration.java
plugins/org.python.pydev/src/org/python/pydev/editor/PyReconciler.java
plugins/org.python.pydev/src/org/python/pydev/editor/actions/codefolding/PyFoldingAction.java
plugins/org.python.pydev/src/org/python/pydev/editor/actions/codefolding/PyUnCollapseAll.java
plugins/org.python.pydev/src/org/python/pydev/editor/codefolding/CodeFoldingSetter.java
plugins/org.python.pydev/src/org/python/pydev/editor/correctionassist/PythonCorrectionProcessor.java

Following changes needed to properly compile against newly generified
code:
* IWorkspace adds two new run methods to be stubbed. (not marked as
Override to allow compilataion against older platform).
* TextSourceViewerConfiguration.getHyperlinkDetectorTargets returns
Map<String, IAdaptable> which was using too specific types in Pydev
code.
* IAnnotationModel.getAnnotationIterator returns Iterator<Annotation> so
some adjustments were needed where more specific types were used.

Fix compile against Neon platform.

---

plugins/org.python.pydev/src/org/python/pydev/ui/pythonpathconf/InterpreterInfo.java
plugins/org.python.pydev/tests/org/python/pydev/ui/pythonpathconf/InterpreterInfoOutput.txt

Needed at least on Linux with 3.4 for e.g. `multiprocessing.Semaphore` to be recognized.

Add multiprocessing to cpython's forced libs

---

plugins/org.python.pydev/pysrc/_pydev_imps/_pydev_execfile.py

tokenize.open() is the best way to read the source file,
but tokenize.open() is only available for python 3.2.
when running at python 3.1 or 3.0,  it have to do detect source file's encoding before read file.

tokenize.open is only available in ver 3.2

---

plugins/org.python.pydev/pysrc/_pydev_runfiles/pydev_runfiles.py
plugins/org.python.pydev/pysrc/runfiles.py

The first two should be self explanatory.
About the third, I don't know what the actual problem is with loading `unittest` before running `pytest.main` as the py.test runner appears to work even with the error message printed, but I suppose the message is there for a reason. So the third commit prevents it, and tests also run faster when the Django imports don't need to be done.

Test runner fixes

---

plugins/org.python.pydev/src/org/python/pydev/editor/hover/PyHoverPreferencesPage.java
plugins/org.python.pydev/src/org/python/pydev/editor/hover/PydevCombiningHover.java

Bugfix: hover preempt was not respected when two hovers have same priority and the first one has preempt set and the second one does not.
Also some minor code cleanup.

fix: hover preempt works with equal prioority markers.

---

plugins/com.python.pydev.refactoring/src/com/python/pydev/refactoring/hyperlink/PythonHyperlink.java

Eclipse support having more than 1 hyperlink detector active for a given
type of document and also allows a given detector to generate more than
one hyperlink object. In order for the user to allow choosing which
'action' to take, these hyperlinks need to provide a meaningful text
from getHyperlinkText as otherwise Eclipse will fill in a dummy text
(Unknown Hyperlink) into the list of hyperlinks for the text region.
So this change adds a short text indicating that the hyperlink
activation will take the user to the definition of the function/class
under the cursor.

Fix display of multiple hyperlinks

---

plugins/org.python.pydev/src/org/python/pydev/plugin/PydevPlugin.java

The problem happened here after the commit: https://github.com/fabioz/Pydev/commit/732347236a67305ffe7ad36b4944910601cf3ba7#diff-89c232ffd444d2489d2e8b58fe1fba4fL517. It added: 
```java
URI locationURI = f.getLocationURI();
```
in [getIResourceOSString](https://github.com/fabioz/Pydev/blob/9fadc08f29675e792150b80165f53f7179af4055/plugins/org.python.pydev/src/org/python/pydev/plugin/PydevPlugin.java#L534) method. When the RTC plugin is installed, ```f.getLocationURI()``` returns something like: 
```
sourcecontrol://jazz/default/serpro.portalcidades/serpro/portalcidades/config.py
```
This is not a valid file path. So, I get an ```IllegalArgumentException```
However, the ```f.getRawLocation()``` which is called just below work.
Fixes #PyDev-622

Fix code analysis when the code is connected to an RTC source control

---

plugins/org.python.pydev/pysrc/_pydev_bundle/pydev_console_utils.py

As mentioned in [715|https://sw-brainwy.rhcloud.com/tracker/PyDev/715], the interactive console (since PyDev 3.6.0) has problems parsing inputs.
This is also commented upon on line 73 of [pydevconsole.py|https://github.com/fabioz/Pydev/blob/master/plugins/org.python.pydev/pysrc/pydevconsole.py].

Fix Jython parsing bug

---

plugins/org.python.pydev.parser/src/org/python/pydev/parser/grammar30/build_linux.xml

Works on Ubuntu 16.04 with the stock javacc/openjdk installed through the package manager.

Added linux ant builder for python3 grammar

---

plugins/org.python.pydev.core/src/org/python/pydev/core/docutils/PySelection.java
plugins/org.python.pydev.debug/src_console/org/python/pydev/debug/newconsole/PydevConsoleInterpreter.java
plugins/org.python.pydev/src_completions/org/python/pydev/editor/codecompletion/PyCodeCompletion.java
plugins/org.python.pydev/tests/org/python/pydev/editor/actions/PySelectionTest.java

At the moment the console will provide completions for after the . (dot) in a number. For example 123. provides bit_length(), conjugate() etc. However these are not valid completions as 123.bit_length() is a syntax error.
However, the primary reason for this pull request is to stop having completion pop-ups in the middle of typing a floating point number. While working on this aspect I realised the suggested completions were not even valid.
A similar thing happens in the editor, but it is less clear to me how to resolve it there. I can see that org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getBuiltinsCompletions(ICompletionState) provides the incorrect completions, and by suppressing completion results with NodeUtils.getBuiltinType(act) returns "int" does seem to …

Suppress invalid completions on literals numbers

---

plugins/org.python.pydev.customizations/templates/google_app_engine/ask_login/app.yaml
plugins/org.python.pydev.customizations/templates/google_app_engine/hello_webapp_world/app.yaml
plugins/org.python.pydev.customizations/templates/google_app_engine/hello_world/app.yaml

- update `.yam`l file for google app engine project templates. 
- According to GAE Docs [Migrate to Python 2.7][1], update the `version:` element and add `threadsafe:` element
- According to GAE Docs [Using WSGI][2], update the `script:` element
- update line break to `LF` for `.yaml` files
[1]: https://cloud.google.com/appengine/docs/standard/python/python25/migrate27#appyaml
[2]: https://cloud.google.com/appengine/docs/standard/python/python25/migrate27#wsgi

Update Google App Engine Project Templates for GAE's update to Python 2.7

---

plugins/org.python.pydev.parser/src/org/python/pydev/parser/grammarcommon/make_replace.py

File doesnot compile as grammar_common_dir path is not written correct (4th line of the code). With small fix I've added it works

Fix errors when compile make_replace.py

---

plugins/org.python.pydev.jython/jysrc/pyedit_marker_example.py
plugins/org.python.pydev.jython/plugin.xml

Eclipse marker types cannot be defined on runtime (in Jython scripts) so
this change provides set of marker types dedicated for Jython scripts.
Following marker types are defined:
`org.python.pydev.jython.problemmarker`
`org.python.pydev.jython.taskmarker`
`org.python.pydev.jython.bookmark`

Add custom marker types for PyDev scripts.

---

plugins/org.python.pydev.customizations/templates/google_app_engine/ask_login/asklogin.py
plugins/org.python.pydev.customizations/templates/google_app_engine/hello_webapp_world/helloworld.py
plugins/org.python.pydev.customizations/templates/google_app_engine/hello_world/app.yaml

I downloaded the Google App Engine SDK: https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.56.zip
But none of the GAE templates supplied with Pydev work with it out-of-the-box. All three templates generate errors in the console when you try to visit the app in your browser at http://localhost:8080/
For each template, I see an error similar to this:
```
ERROR    2017-08-03 21:08:18,001 wsgi.py:263] 
Traceback (most recent call last):
File "/home/mbooth/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
File "/home/mbooth/google_appengine/google/appengine/runtime/wsgi.py", line 302, in _LoadHandler
raise err
ImportError: <module 'helloworld' from …
```

Fix Google App Engine templates that don't work out-of-the-box.

---

plugins/org.python.pydev/pysrc/pydev_ipython/qt_loaders.py

ImportDenier (as used by commitAPI etc.) requires `__forbidden` to be a collection.  This backports the implementation from ipython upstream.
Backports fix:
https://github.com/ipython/ipython/issues/5932/
https://github.com/ipython/ipython/pull/5933

RAP-433 Fix ImportDenier implementation

---

plugins/org.python.pydev/pysrc/interpreterInfo.py

I recently ran into some problems reinstalling the Cygwin python interpreter into PyDev on an install where it was previously working.
Specifically, Eclipse wasn't able to use the Cygwin python interpreter with the Cygwin DLL version 2.5.2 and later to discover the various paths - interpreterInfo.py was failing:
[~] $ python /c/dev/eclipse-cpp-neon-1a-win32-x86_64/plugins/org.python.pydev_5.4.0.201611281236/pysrc/interpreterInfo.py
Traceback (most recent call last):
File "/c/dev/eclipse-cpp-neon-1a-win32-x86_64/plugins/org.python.pydev_5.4.0.201611281236/pysrc/interpreterInfo.py", line 207, in <module>
prefix = tounicode(native_path(sys.prefix))
File "/c/dev/eclipse-cpp-neon-1a-win32-x86_64/plugins/org.python.pydev_5.4.0.201611281236/pysrc/interpreterInfo.py", line 71, in native_path …

fix problem with Cygwin dlopen

---

plugins/org.python.pydev/build.properties

These files are only needed if you are developing Pydev or needed only by CI systems, they shouldn't be shipped in the binary distribution of Pydev itself.

Omit hidden project files and CI files from org.python.pydev bundle

---

plugins/org.python.pydev/src/org/python/pydev/editor/preferences/PydevEditorPrefs.java

There is a small bug in the new ["subword" navigation editor preference][1]:  It is impossible to switch back to the "Native" setting.
Disclaimer: I'm pretty sure this tiny PR will fix the issue, but I'm unable to test it myself.
**Edit:** To reproduce the bug, simply open Preferences > PyDev > Editor and select "Native" for the "Word navigation" setting.  Then close the Preferences window and re-open it.  The setting will say "Subword" again, because it never really changed.
[1]: http://pydev.blogspot.com/2017/09/pydev-60-pip-conda-isort-and-subword.html

Fix logic error in editor preferences for subword navigation.

---

plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/AnalysisPreferenceInitializer.java
plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/AnalysisPreferences.java
plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/IAnalysisPreferences.java
plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/OccurrencesAnalyzer.java
plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/messages/AbstractMessage.java
plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/messages/IMessage.java
plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/ui/AnalysisPreferencesPage.java
plugins/org.python.pydev.core/src/org/python/pydev/core/FileUtilsFileBuffer.java
plugins/org.python.pydev.core/src/org/python/pydev/core/IMiscConstants.java
plugins/org.python.pydev.core/tests/org/python/pydev/core/EncodingsTest.java
plugins/org.python.pydev.shared_core/src/org/python/pydev/shared_core/io/FileUtils.java
plugins/org.python.pydev.shared_core/src/org/python/pydev/shared_core/io/PyUnsupportedEncodingException.java
plugins/org.python.pydev/src/org/python/pydev/editor/PyEdit.java
plugins/org.python.pydev/src/org/python/pydev/editor/actions/PyFormatStd.java
plugins/org.python.pydev/tests_completions/org/python/pydev/editor/codecompletion/revisited/PythonPathHelperTest.java

Refactors the getPythonFileEncoding methods so that we can tell the
difference between "no encoding was declared" and "the declared
encoding is invalid" so that we can use the information during code
analysis to create problem markers in the latter case.
Previously, when Pydev detected an unsupported encoding, it would
just dump a stacktrace into the log and silently continue without
informing the user. With this change, Pydev will inform the user
instead of polluting the log.
Signed-off-by: Mat Booth <mat.booth@redhat.com>

Add problem markers for python files that declare invalid encodings

---

plugins/org.python.pydev.shared_interactive_console/src/org/python/pydev/shared_interactive_console/console/ui/internal/ScriptConsoleMessages.java
plugins/org.python.pydev.shared_interactive_console/src/org/python/pydev/shared_interactive_console/console/ui/internal/ScriptConsoleMessages.properties
plugins/org.python.pydev.shared_interactive_console/src/org/python/pydev/shared_interactive_console/console/ui/internal/ScriptConsolePage.java

In the latest Pydev (6.3.2) we noticed that the translations for the interactive console actions were broken
See this screenshot for an illustration of the problem: https://ibin.co/3xKYxpoJHNMO.jpg
Signed-off-by: Mat Booth <mat.booth@redhat.com>

Fix translations for the interactive console view

---

plugins/org.python.pydev.core/META-INF/MANIFEST.MF
plugins/org.python.pydev.core/src/org/python/pydev/core/CorePlugin.java

On Linux, some special files such as named pipes may present as zero-length files. When PyDev attempts to read these with a blocking read, it blocks the UI thread indefinitely if the pipe contains no data. By simply checking if the file is zero-length before reading it PyDev can avoid this.

Ignore zero-length files

---

plugins/org.python.pydev.shared_interactive_console/src/org/python/pydev/shared_interactive_console/console/ui/internal/ScriptConsoleDocumentListener.java
plugins/org.python.pydev.shared_interactive_console/src/org/python/pydev/shared_interactive_console/console/ui/internal/ScriptConsoleMessages.java
plugins/org.python.pydev.shared_interactive_console/src/org/python/pydev/shared_interactive_console/console/ui/internal/ScriptConsoleMessages.properties
plugins/org.python.pydev.shared_interactive_console/src/org/python/pydev/shared_interactive_console/console/ui/internal/ScriptConsolePage.java
plugins/org.python.pydev.shared_interactive_console/src/org/python/pydev/shared_interactive_console/console/ui/internal/ScriptConsoleViewer.java
plugins/org.python.pydev.shared_interactive_console/src/org/python/pydev/shared_interactive_console/console/ui/internal/actions/ScrollLockAction.java

i have implemented a 'Scroll Lock' action (button), for the interactive console, very similar in look and feel to the 'word wrap' action.
found it necessary  for continues printouts and loops..
[[https://www.brainwy.com/tracker/PyDev/920]](https://www.brainwy.com/tracker/PyDev/920)
Default behaviour will stay the same(normal scroll to end of text). click on the button will toggle scroll lock state.

implement new scrollLock action for interactive console

---

plugins/org.python.pydev/src/org/python/pydev/editor/codefolding/CodeFoldingSetter.java
plugins/org.python.pydev/src/org/python/pydev/editor/codefolding/FoldingEntry.java
plugins/org.python.pydev/src/org/python/pydev/editor/codefolding/PyDevCodeFoldingPrefPage.java
plugins/org.python.pydev/src/org/python/pydev/editor/correctionassist/docstrings/DocstringsPrefPage.java
plugins/org.python.pydev/tests/org/python/pydev/editor/codefolding/CodeFoldingSetterTest.java

Passed unit testing. UI tests looked good although it is worth noting that several cases confuse the code folding. I think that is OK. As long as properly formatted '# region ', '#region ', '# endregion ', '#endregion ' (not the trailing space) tags are used the code folding works.

Ticket 694: Add code folding functionality via the #region and #endregion tags

---

plugins/org.python.pydev.debug/src/org/python/pydev/debug/model/PyDebugModelPresentation.java
plugins/org.python.pydev.debug/src/org/python/pydev/debug/model/PyVariable.java
plugins/org.python.pydev.debug/src/org/python/pydev/debug/model/PyVariableCollection.java
plugins/org.python.pydev.debug/src/org/python/pydev/debug/model/PyWatchExpressionDelegate.java
plugins/org.python.pydev.debug/src/org/python/pydev/debug/model/XMLUtils.java

This PR provides several stuff:
1. A fix on the editor opened by default when clicking on a breakpoint (see e678894); 
2. A fix to read the qualifier returned by the <var /> tag
3. A fix when the <xml /> is empty, leaving ArrayIndexOutOfBoundsException

Use editor based on content type rather than forcing it and fix some errors in watch expression

---

plugins/com.python.pydev.docs/homepage/final/history_pydev.html
plugins/com.python.pydev.docs/homepage/history_pydev.contents.rst_html
plugins/com.python.pydev.docs/homepage/history_pydev.rst

If I understand correctly, when we have ```#PyDev-xxx``` in the changelog, ```xxx``` refers to the ticket https://www.brainwy.com/tracker/PyDev.
PR #184 fix ticket https://www.brainwy.com/tracker/PyDev/622 and not tickt ```184```. I think you have put the PR number instead of the ticket number.

Fix ticket number in changelog

---

plugins/org.python.pydev/src/org/python/pydev/editor/PyInformationPresenter.java

When using the org.python.pydev.pydev_hover2 extension point it is possible to add new hover info. When the hover info contains a pydev_link (through ItemPointer.asPortableString()) those links are clickable in the hover popup and will open the corresponding pointer.
Currently this does not work correctly because PyStyleRange.similarTo(StyleRange) is not implemented which causes all PyStyleRanges to be "similar" even though they have different pointers.
The StyledTextRenderer optimizes its memory consumption and discards similar style ranges.
This causes all links to point to the first pydev_link.
This pull request fixes the behaviour by taking the link pointer into account when comparing PyStyleRange for similarity.
As this is my first pull request for PyDev, please let me know if you …

Fix hover links when different pydev_link pointers are used

---

plugins/org.python.pydev.debug/src/org/python/pydev/debug/model/AbstractDebugTarget.java

The code to track user input in process console relies on some non-public
classes/methods from which one is [removed](https://bugs.eclipse.org/bugs/show_bug.cgi?id=548356) in a future eclipse version. This
replace the removed method call with an equivalent workaround.
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=548356#c4 ff.

Update code tracking user input in console

---

plugins/org.python.pydev.core/pysrc/_pydev_bundle/_pydev_completer.py

For non-english language, urllib.quote cannot automatically transfer unicode characters to utf8 and thus will reach an error indicate that there is a key error for quote.
A simple way to resolve this is to transfer all unicode item to utf8.

bugfix completion for non-english language

---

plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/refactoring/quick_fixes/AddTokenAndImportStatement.java
plugins/org.python.pydev/tests_analysis/com/python/pydev/analysis/refactoring/quick_fixes/AddTokenAndImportStatementTest.java

Fixes:
- automatic group imports don't recognize imports strings with comments
- commas trailing
- automatic import gets import end offset wrong when import comment has ")" in it
- import string concats wrongly when it has spaces and tabs
- import string concats wrongly when it style is "(aaa,)" or "(aaa  )", or "(aaa,  )", or "(aaa)  " or others similar styles
Changes:
- added two new functions: getOffsetDiff and getOffset
- now all import strings have a standard style
- imports are RIGHT trimmed when it doesn't have comments in
- after implementing the fixes, all unused old variables were deleted
Observations:
- all changes are compatible to correctly agroup similar imports to an import string with spaces and tabs before (because it doesn't trim import string), but the project class …

Fix for #PyDev-542: Automatic import doesn't check for trailing comma

---

.gitignore
plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/visitors/OccurrencesVisitor.java
plugins/org.python.pydev.parser/src/org/python/pydev/parser/grammar_fstrings/FStringsGrammar.java
plugins/org.python.pydev.parser/src/org/python/pydev/parser/grammar_fstrings/FStringsGrammarFactory.java
plugins/org.python.pydev.parser/src/org/python/pydev/parser/grammar_fstrings/build.xml
plugins/org.python.pydev.parser/tests/org/python/pydev/parser/FStringsParserTest.java
plugins/org.python.pydev/src/org/python/pydev/editor/PyFStringScanner.java

I created a new factory class to handle f-strings and check if it has a scape unicode character before code f-string variables definition.
I also ran JavaCC build.xml, so some code changes were automatic generated

Fix for #PyDev-1055: Pydev does not recognize named unicode character escape in f-string

---

plugins/org.python.pydev.core/pysrc/_pydev_bundle/pydev_monkey_qt.py
plugins/org.python.pydev.core/pysrc/_pydevd_bundle/pydevd_command_line_handling.py
plugins/org.python.pydev.debug/src/org/python/pydev/debug/ui/launching/PythonRunnerConfig.java
plugins/org.python.pydev/src/org/python/pydev/plugin/preferences/PyDevEditorPreferences.java

I believe pyside2 basic debugging support was already there, but would be triggered just if using "auto" and this can be problematic when having multiple Python Qt bindings installed. Also the comments and error messages may mislead the user into thinking it is not really supported.
This PR just explicitly adds also the handling for pyside2 option.

handle also pyside2 in command line (as it is indeed internally handled correctly internally)

---

plugins/org.python.pydev.ast/src/org/python/pydev/ast/codecompletion/revisited/AssignAnalysis.java
plugins/org.python.pydev.ast/src/org/python/pydev/ast/codecompletion/revisited/CompletionState.java
plugins/org.python.pydev.ast/src/org/python/pydev/ast/codecompletion/revisited/CompletionStateWrapper.java
plugins/org.python.pydev.ast/src/org/python/pydev/ast/codecompletion/revisited/modules/SourceModule.java
plugins/org.python.pydev.core/src/org/python/pydev/core/ICompletionState.java
plugins/org.python.pydev/tests/pysrc/findActualDefinition/bar.py
plugins/org.python.pydev/tests/pysrc/findActualDefinition/foo.py
plugins/org.python.pydev/tests_completions/org/python/pydev/ast/codecompletion/revisited/FindActualDefinitionTest.java

The problem was that the visitorScope was not being defined correctly. Even though it was the same token (with the last part trimmed), the visitorScope line and column parameters were being setted different

Fix for #Pydev 1075: Go to definition issue

---

plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/refactoring/quick_fixes/AddTokenAndImportStatement.java
plugins/org.python.pydev/tests_analysis/com/python/pydev/analysis/refactoring/quick_fixes/AddTokenAndImportStatementTest.java

The problem was that `int lastImportedStrOffset` was being assigned with String` indexOf(String)` method, so if any import had the same start as the import to be added, the offset would be stored wrong. So I changed all the offset search approach

Fix for #Pydev 1085: Adding auto-import to wrong location

---

plugins/org.python.pydev/src/org/python/pydev/ui/pythonpathconf/PackageTab.java

This would be useful whenever the user should not be allowed to (easily)
make changes to the conda or pip environments.
We work at a facility with a conda installation that is used by hundreds of users, with many using PyDev, and of which a substantial subset have sufficient privileges to modify the environment, even though that may be a bad idea...
This commit introduces support for a system property whose value will be checked to determine whether the package manager buttons in the CPython interpreter preferences screen should be enabled or disabled. The default will be to enable them.

Add option to disable CPython package manager buttons

---

plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/AnalysisPreferences.java
plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/refactoring/quick_fixes/UndefinedVariableQuickFixCreator.java
plugins/com.python.pydev.analysis/src/com/python/pydev/codecompletion/ctxinsensitive/CtxParticipant.java
plugins/com.python.pydev.analysis/src/com/python/pydev/codecompletion/participant/ImportsCompletionParticipant.java
plugins/org.python.pydev/src/com/python/pydev/analysis/ctrl_1/UndefinedVariableFixParticipant.java
plugins/org.python.pydev/src/com/python/pydev/analysis/organizeimports/OrganizeImports.java
plugins/org.python.pydev/src/org/python/pydev/editor/codefolding/CodeFoldingSetter.java
plugins/org.python.pydev/tests/org/python/pydev/editor/codefolding/CodeFoldingSetterTest.java

A product shipping PyDev plugins may want to override the default values
for certain preference settings. This can be done by specifying the
intended value inside a plugin_customizations.ini file that is loaded as
part of the product. The Eclipse eco-system will ensure that these values
land in the DefaultScope.INSTANCE preference instead of the values set
via the corresponding PreferenceInitializer classes.
In order to ensure those changed defaults are actually used one either has
to use an EclipsePreferenceStore instance that handles lookup through both
the instance and the default scope, explicitly use the
DefaultScope.INSTANCE for determining the default-value-argument or as
a third option use the IEclipsePreferenceService' API for accessing the
preference keys.
These two places used …

Allow overriding of two more preferences via plugin_customizations.ini

---

plugins/org.python.pydev.core/pysrc/_pydev_runfiles/pydev_runfiles_unittest.py

Fixes: https://www.brainwy.com/tracker/PyDev/1096
When an SkipTest Exception is thrown, the RPC Server will get notified of this an mark the test as Skip.
As I am not that deep into the codebase I am not sure if this is the "right" approach.
It works for my case, but if there is a better way please guide me in the right direction to implement it.
Thanks a lot for this awesome project!

[1096] Mark Skiped Tests as Skip in Overview

---

plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/pylint/PyLintAnalysis.java
plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/pylint/PyLintAnalysisTest.java

https://www.brainwy.com/tracker/PyDev/1107
When pylint message contains round brackets, it incorrectly parses output and shows in problems view as "PyLint:" intead of "PyLint: Line too long (106/100)"
#Hacktoberfest (please add label hacktoberfest-accepted to this PR)

Issue 1107 pylint message

---

plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/scopeanalysis/AbstractScopeAnalyzerVisitor.java
plugins/org.python.pydev/tests_analysis/com/python/pydev/analysis/OccurrencesAnalyzerPy38Test.java

I ran all the tests and all seems to work fine ;)

Fix for #Pydev 1125: Undefined variable in return type annotations for classes "in construction" even when annotations are imported from __future__

---

plugins/org.python.pydev.core/pysrc/_pydev_imps/_pydev_saved_modules.py

Jython doesn't have start_new in the thread module since it is [obsolete](https://www.jython.org/jython-old-sites/archive/21/docs/differences.html) ("CPython's thread modules defines some aliases that Jython's doesn't. These aliases are considered obsolete and won't be supported by Jython."), so looking for it causes pydev to fail.  I ran into this when using Ghidra. You can see my comments the issue thread [here](https://github.com/NationalSecurityAgency/ghidra/issues/3378#issuecomment-931878167).
I don't know if this is the right fix or not, but I did not see start_new used in this codebase. I do see what looks like a monkey patch to add start_new [here](https://github.com/fabioz/Pydev/blob/cd7bb8c3df5cd3231c2bb4d4954e0314a920afb0/plugins/org.python.pydev.core/pysrc/_pydev_bundle/pydev_m …

remove check for start_new in thread so jython works

---

plugins/org.python.pydev/src/org/python/pydev/editor/PyInformationPresenter.java

The offset might be invalid when a user clicks on a location which is after the last character of a line.
The existing check no longer works, because `getOffsetAtPoint` only throws an `IllegalArgumentException` when the given Point is `null`.

Check if offset is valid before using it

---

plugins/org.python.pydev.debug/src/org/python/pydev/debug/ui/propertypages/BreakpointConditionEditor.java
plugins/org.python.pydev.debug/src/org/python/pydev/debug/ui/propertypages/PythonBreakpointPage.java

Eclipse 2024-03 [removed some APIs](https://github.com/eclipse-platform/eclipse.platform.ui/commit/e4b25da2b208741708350af58695b60c89cd3fcb#diff-716a1126cf01ecec5f99055d895b014bdc706c1af6b403bda55ce700c017aaee) that have been deprecated for several years. Some of these APIs have been used in the Breakpoint Property Editor to enable/disable the handlers used for code completion of conditional breakpoints. However, code completion for conditional breakpoints seems to have been commented out for > 18 years. So I went ahead and removed the commented code as well the usages of the deprecated APIs.
I know that a better but much more time consuming solution would have been to reimplement code completion, but I currently don't have the time to do this. Since the code completition wasn't working …

Remove left-overs of code completion in breakpoint properties

---

plugins/com.python.pydev.debug/src/com/python/pydev/debug/model/ProcessServer.java

It's currently not possible to stop the Debug Server, because the underlying ProcessServer does not support proper termination.
The following code is used to shutdown the process:
https://github.com/eclipse-platform/eclipse.platform/blob/ebe8db5d9d1c7d231be261d9fd5207dfc94ca9a0/debug/org.eclipse.debug.core/core/org/eclipse/debug/core/model/RuntimeProcess.java#L243-L293
The call to `waitFor(...)` queries the exit value of the process, which always throws an `IllegalThreadStateException`, indicating that the process is still running, and thus leading to a timeout. I changed the implementation, such that `exitValue()` returns  zero, if the process has been terminated.
The easiest way to reproduce this is to start/stop the debug server via the Pydev menu. When stopping the server, the UI will …

Enable proper termination of ProcessServer

---

plugins/com.python.pydev.analysis/src/com/python/pydev/analysis/flake8/Flake8Analysis.java

When flake8 location is specified directly, the arguments are before the command rather than after so it does not run

Reorder commands for flake8 when binary chosen directly
